### ISSUE TITLE
Is the readme correct?

### ISSUE THREAD

**Issue by Denubis** [ONLYOFFICE/plugin-zotero#2]
Hi @LinneyS -- the readme says this plugin is bundled with the server. Is the readme correct, or is this a stock template and not yet provisioned?

**Comment by Eloncase** [comment]
Hi @Denubis.
The readme is correct. Zotero plugin is available for manual installation on a Document Server and Integration Edition and is bundled with the rest.

**Comment by alexpattyn** [comment]
Just wanted to clarify some things. The readme says it is pre-installed on the Community Edition, does that include the version that comes with nextcloud hub? Wasn't sure if that falls under "Document Server integrated with a 3rd-party storage".

Then would the plug-in only work with the web editor? Since it would be nice to have on the desktop editor, and there have been some (dead-end) discussions of it on the forms. 

https://forums.zotero.org/discussion/79081/zotero-pluggin-for-onlyoffice
https://cloud.onlyoffice.org/viewtopic.php?p=25515&sid=9e2913c3e2ba960c2e2228665df273b2#p25515
https://dev.onlyoffice.org/viewtopic.php?f=9&t=9900&p=27740&hilit=zotero#p27740
https://dev.onlyoffice.org/viewtopic.php?f=9&t=24413&p=32803&hilit=zotero#p32803

**Comment by ShockwaveNN** [comment]
Right now README file contains all installation instructions and details about where plugin installed by default so I'm closing this
